### ISSUE TITLE
Add to Zalenium docs?

### ISSUE THREAD

**Issue by diemol** [gswallow/helm-zalenium#1]
Hi @gswallow,

This looks great! Would you like to mention it in the Zalenium k8s documentation? Maybe around [here](https://github.com/zalando/zalenium/blob/master/docs/k8s/kubernetes.md#starting-with-kubernetes) or adding a new markdown page and linking it from there?

Thanks for creating this package,

**Comment by gswallow** [comment]
Hi,

Thanks!  I did this project as one of the last things I could tackle,
mainly out of boredom, at my last job, which ended two Fridays ago.

I work in an entirely different world now so I don't foresee myself adding
different storage classes and RBAC to the helm chart, but I could.  Do you
guys just want to take the code or maybe have me merge it in?

**Comment by diemol** [comment]
Hi,

Sorry for the late reply. 

I think we could add it to the repo, perhaps someone finds it useful and we could support it. It would be nice if you can merge it since you are the author, perhaps under the docs/k8s and reference it from the k8s main doc?

Thanks again,

**Comment by diemol** [comment]
Thanks!
